# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"


set -g mouse on               # Enable mouse for scrolling/resizing
set -s escape-time 0          # Faster command sequences
# set -g base-index 1           # Start windows at 1 (easier to reach)
# setw -g pane-base-index 1     # Start panes at 1
set -g renumber-windows on    # Automatically renumber windows when one is closed

# --- Key Bindings ---
# Remap prefix from 'C-b' to 'C-a' (easier on the pinky)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Easy config reload
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Split panes using | and - (more intuitive than % and ")
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch panes using Alt-arrow without prefix
# bind -n M-Left select-pane -L
# bind -n M-Right select-pane -R
# bind -n M-Up select-pane -U
# bind -n M-Down select-pane -D

# --- DIY Visuals ---
# set -g status-position top       # Move status bar to the top (modern feel)
set -g pane-border-style fg='#6272a4'
set -g pane-active-border-style fg='#ff79c6'

# Custom Status Bar Layout
set -g status-style bg=default,fg=white

set -g status-left-length 20
set -g status-left "#[fg=green,bold]#S " # Show Session Name

# set -g status-right-length 100
set -g status-right "#[fg=green] %d.%m.%Y #[fg=white]|#[fg=green] %H:%M:%S "

# Highlight the active window tab
setw -g window-status-current-format "#[fg=black,bg=white,bold] #I:#W #[default]"
setw -g window-status-format "#[fg=white,bg=default] #I:#W "
set-window-option -g window-status-current-style fg=black,bg=green

# Popups
# bind C-j display-popup -h 15 -w 30 -E "tmux-session-switcher"
# bind C-j display-popup -h 15 -w 30 "tmux-session-switcher; read"

